### ISSUE TITLE
i have a problem

### ISSUE THREAD

**Issue by guojun1992** [google/gops#6] opened 2016-11-14 09:29 UTC
go build
package .
	imports github.com/google/gops/internal/objfile: use of internal package not allowed

**Comment by siadat** [comment] 2016-11-14 14:15
I can't reproduce this issue. I can only suggest doing a few things :)

- Report the output of `go version`
- Make sure you have the latest version of gops and git status says your working directory is clean
- Make your issue a bit more readable. Use markdown to format the terminal output by prefixing terminal lines with 4 spaces

For example:

    $ go build

I hope this helps :)

**Comment by rakyll** [comment] 2016-11-14 17:24
This issue should have been resolved via https://github.com/google/gops/issues/2.

Update the package by running:
```
go get -u github.com/google/gops
```
Reopen this issue if you keep experiencing it with the outputs of `go version` and `go env`.

**Closed by rakyll** 2016-11-14 17:24 UTC

**Comment by guojun1992** [comment] 2016-11-29 04:13
i have read this code
https://github.com/google/gops/blob/master/main.go#L15
the internal dir is the package inter vendor， i think there should “internal/objfile” but not ”github.com/google/gops/internal/objfile“

i have read golang std package
see https://github.com/golang/go/blob/f4c997578ad962074b8e3aaf28dcfaa2f48a8593/src/cmd/compile/internal/mips/galign.go#L9

**Comment by guojun1992** [comment] 2016-11-29 04:14
my go version is 1.7.1，thinks for your help
